#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CPTCAppNew.Droid.Resource", IsApplication=true)]

namespace CPTCAppNew.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blacklogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int email1x = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int events1x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_canvas = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_email = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_events = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_info = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_map = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int iconcanvas1x = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int info1x = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int map1x = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int programs1x = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int settings1x = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int RelativeLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int btn_canvas = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int email = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int emailWebView = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int events = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int imageView1 = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int info = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int map = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int settings = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int tableLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int tableRow1 = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int tableRow2 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int tableRow3 = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int webView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Canvas = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int email = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Events = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int generalinfo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Map = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Settings = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int Canvas = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int Events = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int email = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int info = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int map = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int settings = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
